#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.my-terminal/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.my-terminal/init.zsh"
fi

# Customize to your needs...

alias tmux_w4="tmux split-window -p 66 \; split-window -d \; split-window -h \;"
alias tmux_w5="tmux split-window -p 66 \; split-window -d \; split-window -h \; select-pane -t 0 \; split-window -h \;"
alias tmux_w6="tmux split-window -h \; split-window -v -p 66 \; split-window -v \; select-pane -t 0 \; split-window -v -p 66 \; split-window -v \;"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mustafas/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mustafas/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mustafas/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mustafas/google-cloud-sdk/completion.zsh.inc'; fi
